version: '3.8'

services:
  db:
    image: postgres:15
    container_name: alignoscope-db
    environment:
      POSTGRES_USER: alignoscope
      POSTGRES_PASSWORD: alignoscope
      POSTGRES_DB: alignoscope
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # 添加初始化脚本目录
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]

  # pgadmin管理工具（可选）
  pgadmin:
    image: dpage/pgadmin4
    container_name: alignoscope-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@alignoscope.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
