"""empty message

Revision ID: 32dccac4ebdc
Revises: 7b5d0d16fee0
Create Date: 2024-11-24 16:40:46.481135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32dccac4ebdc'
down_revision = '7b5d0d16fee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jeanchristoph')
    with op.batch_alter_table('jeanchristophe', schema=None) as batch_op:
        batch_op.drop_column('volume')
        batch_op.drop_column('block_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jeanchristophe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_number', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('volume', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))

    op.create_table('jeanchristoph',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lang0', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True),
    sa.Column('lang1', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
