"""empty message

Revision ID: 7b5d0d16fee0
Revises: 
Create Date: 2024-11-24 16:15:18.631695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b5d0d16fee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jeanchristophe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang0', sa.Text(), nullable=True),
    sa.Column('lang1', sa.Text(), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jeanchristoph')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jeanchristoph',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lang0', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True),
    sa.Column('lang1', mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.drop_table('jeanchristophe')
    # ### end Alembic commands ###
